/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfe;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;

/**
 *
 * @author simo
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        try
		{
			Image iconAcc=ImageIO.read(new File("icon.png"));
			this.setIconImage(iconAcc);
		}catch(IOException e)
		{
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Resultat");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 30, 240, 30);

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 360, 240, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Resultat");
        jButton1.setActionCommand("resultat");
        jButton1.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\simo\\Desktop\\IMG_20160523_151724497.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 410, 110, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("mensuel");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 370, 110, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 204, 255));
        jLabel8.setText("echelle");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 210, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 255));
        jLabel5.setText("corps");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 120, 60, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 204, 255));
        jLabel6.setText("grade");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 180, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 255));
        jLabel4.setText("cadre");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 150, 80, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 255));
        jLabel7.setText("categorie");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 90, 90, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 204, 255));
        jLabel9.setText("region");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 240, 60, 40);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(130, 100, 90, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(130, 130, 90, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(130, 190, 90, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(130, 160, 90, 20);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(130, 220, 90, 20);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(130, 250, 90, 20);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton1.setText("Retoure");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(520, 350, 100, 25);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jTextField8);
        jTextField8.setBounds(130, 290, 200, 21);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Criditeur");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 290, 80, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Quitte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(647, 420, 90, 23);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(0, 0, 255));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(130, 420, 240, 30);

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(0, 0, 255));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11);
        jTextField11.setBounds(130, 390, 240, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 255));
        jLabel12.setText("salaire nett");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 400, 70, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 255));
        jLabel13.setText("LE RESTE");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 420, 90, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("CREDIT DEMANDE");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 320, 130, 40);

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jTextField10);
        jTextField10.setBounds(130, 330, 200, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("RISQUE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(660, 380, 100, 23);

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(jTextField12);
        jTextField12.setBounds(130, 450, 240, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Resultat");
        jLabel14.setToolTipText("");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 450, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\simo\\Documents\\NetBeansProjects\\Pfe\\Article-Deep-learning.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          int m=0,a=0,cols=0,rows=0,g=0;
        int  iter=0;
        double []poids=new double[50];
        for(int i=0;i<50;i++)
            poids[i]=0 ;
        Node n =new Node();
        double h =Double.valueOf(this.jTextField2.getText());
         double b =Double.valueOf(this.jTextField3.getText());
          double c =Double.valueOf(this.jTextField4.getText());
          double d =Double.valueOf(this.jTextField5.getText());
          double e =Double.valueOf(this.jTextField6.getText());
           double f =Double.valueOf(this.jTextField7.getText());
          
         double[][] matr={{h,b,c,d,e,f}};
	    		    try {
                                Maps M =new Maps();
                                 iter=M.appretissage(matr);
                               System.out.println(iter);
                     
        File fi=new File("sortiegross.txt");
	FileReader F1;
        
            F1 = new FileReader(fi);
         
        
	String ligne2;
     
	
     
     StringTokenizer st;
     BufferedReader sortie_poids=null;
          sortie_poids=new BufferedReader(new FileReader("sortiegross.txt"));
		
           while((ligne2=sortie_poids.readLine())!=null){
              a=0;
              st=new StringTokenizer(ligne2," ");
           
              
              poids[m]=Double.valueOf(st.nextToken()).doubleValue();
            //  ner[m].Weight_of_Node[a]=poids[m][a];
             
               
              
             // g++;
             m++;
              rows=m;
              cols=a;
            
              
          }
    
                               
                               
                               
					} catch (IOException e1) {
						e1.printStackTrace();
					}
        String chaine="ff";
        chaine = chaine.valueOf(poids[iter]) ;
        this.jTextField1.setText(chaine);
      System.out.print(poids[iter] );
      //la monsuel
        double traite = Double.valueOf(this.jTextField1.getText()).doubleValue();
        //cridet dans un autre banque
      double debit= Double.valueOf(this.jTextField8.getText()).doubleValue();
      
      double vv =(traite*100)/45 ;
      this.jTextField11.setText(String.valueOf(vv));
      double total  =  traite -debit ;
      this.jTextField9.setText(String.valueOf(total) );
     double  pourcantage= (debit*100)/total ;
     // this.jTextField10.setText(String.valueOf(pourcantage));
     
     
     if (iter<19){
         //this.jTextField13.setText(" enseignment superieure " );
   }else {
     //     this.jTextField13.setText(" Education national " );
     }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
 vainceur P=new vainceur();
 
 this.setVisible(false);
 P.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        
   
        double a = Double.valueOf(this.jTextField9.getText()).doubleValue()-Double.valueOf(this.jTextField10.getText()).doubleValue();
        
        if(a>=0){
        this.jTextField12.setText(" Validee ");
        }else{
        this.jTextField12.setText(" Person Risquee ");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
